### ISSUE TITLE
feature: `save_if_exists` should warn if input is not data-frame-like

### ISSUE THREAD

**Issue by jdhoffa** [RMI-PACTA/pacta.portfolio.utils#37]
Do/ should we expect a warning in this case?

_Originally posted by @jdhoffa in https://github.com/RMI-PACTA/pacta.portfolio.utils/pull/36#discussion_r1580614501_

**Comment by cjyetman** [comment]
Actually, I think that was the main point of `save_if_exists()`, which may not be a great strategy, but I believe the original idea for it was that we need to save a bunch of objects, some times they don't exist (depending on various options), so we wanted to have simple code to just save each of them *if* they exist and otherwise just move on to the next one without a fuss if it doesn't (because that's a situation expected to happen frequently), so no warning or error in that situation was the desired feature.

**Comment by cjyetman** [comment]
In workflow.pacta I stopped using `save_if_exists()`, so ultimately this should be removed/deprecated in the near-to-mid-term, so I think it's best not to mess with its behavior.
